# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - parsebot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://kustaad.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_76fc37f38f054059a5865a3964fe7d7b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ccf54083e764409f9f3e63c3ba70e1b2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: kustaad.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_76fc37f38f054059a5865a3964fe7d7b }}/kustaad:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'parsebot'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0680194d09534881badf7cc2fda73e83 }}
        images: 'kustaad.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_76fc37f38f054059a5865a3964fe7d7b }}/kustaad:${{ github.sha }}'